version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      # dockerfile: Dockerfile
    ports:
      - 8080:80
    # volumes:
    #   - /home/ubuntu/ssl:/etc/nginx/certs

  backend:
    restart: always
    container_name: backend
    build: ./backend
    expose:
      - 5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=api.py
      - FLASK_DEBUG=1
